name: MarFS CI
# There should be some way to use the workflow from the erasureUtils repo instead of duplicating the code from its
# workflow, but I haven't been able to get it to work, so we're going to do this manually

on:
  push:
  pull_request:

jobs:
  Build:
    env:
      Isal_assembler: "nasm"
      Ne_deps: "autoconf libxml2-dev openmpi-bin openmpi-common libopenmpi-dev"
      Marfs_deps: "libfuse libfuse-dev"
      CFLAGS: "-I$GITHUB_WORKSPACE/install/include"
      LDFLAGS: "-L$GITHUB_WORKSPACE/install/lib"
    runs-on: ubuntu-22.04
    steps:
    - name: Install Build Dependencies
      run: sudo apt-get install $Isal_assembler $Ne_deps $Marfs_deps

    - name: Create Install Location
      run: |
        mkdir install

    - name: Checkout ISA-L
      uses: actions/checkout@v3
      with:
        repository: intel/isa-l
        ref: v2.30.0
        path: isa-l

    - name: Checkout erasureUtils
      uses: actions/checkout@v3
      with:
        repository: gransom/erasureUtils
        ref: main
        path: erasureUtils

    - name: Checkout MarFS
      uses: actions/checkout@v3
      with:
        path: marfs

    - name: Build ISA-L
      run: |
        cd isa-l
        ./autogen.sh
        ./configure --prefix="$GITHUB_WORKSPACE/install"
        make install
        cd $GITHUB_WORKSPACE

    - name: Build erasureUtils
      run: |
        cd erasureUtils
        ./autogen.sh
        ./configure --prefix="$GITHUB_WORKSPACE/install"
        make install
        cd $GITHUB_WORKSPACE

    - name: Build and Check MarFS
      run: |
        cd marfs
        ./autogen.sh
        ./configure --prefix="$GITHUB_WORKSPACE/install" --enable-debugALL
        make
        make check
        make install
        cd $GITHUB_WORKSPACE

